# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.go.1.26.6.amd64.stamp: .container/base/deps/go/url.deps .container/base/deps/go/version.deps
	M6E_DEPS_STAGE=base TARGETARCH=amd64 .makefile/container/scripts/fetch.sh go
	touch $@

.container/base/deps/go/amd64.hash.deps: $(FETCH_PATH)/.go.1.26.6.amd64.stamp
	M6E_DEPS_STAGE=base TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh go

PREREQUISITES += .container/base/deps/go/amd64.hash.deps

$(FETCH_PATH)/.go.1.26.6.arm64.stamp: .container/base/deps/go/url.deps .container/base/deps/go/version.deps
	M6E_DEPS_STAGE=base TARGETARCH=arm64 .makefile/container/scripts/fetch.sh go
	touch $@

.container/base/deps/go/arm64.hash.deps: $(FETCH_PATH)/.go.1.26.6.arm64.stamp
	M6E_DEPS_STAGE=base TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh go

PREREQUISITES += .container/base/deps/go/arm64.hash.deps

$(FETCH_PATH)/.go.1.26.6.riscv64.stamp: .container/base/deps/go/url.deps .container/base/deps/go/version.deps
	M6E_DEPS_STAGE=base TARGETARCH=riscv64 .makefile/container/scripts/fetch.sh go
	touch $@

.container/base/deps/go/riscv64.hash.deps: $(FETCH_PATH)/.go.1.26.6.riscv64.stamp
	M6E_DEPS_STAGE=base TARGETARCH=riscv64 .makefile/container/scripts/update-hash.sh go

PREREQUISITES += .container/base/deps/go/riscv64.hash.deps

